name: Node.js CI

on:
  push:
    branches:
      - main  # Replace 'main' with your main branch name (e.g., master, main, etc.)

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # You can choose a different operating system if required.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19.1.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Replace 'build' with your actual build script if different.

      - name: Test
        run: npm test  # Replace 'test' with your actual test script if different.
